### ISSUE TITLE
Maw of the ice dragon on exit not working

### ISSUE THREAD

**Issue by Eein** [Eein/octopath-autosplitter#28]
Had a report from streamer `Yoszarian` that this split did not work on exit - need to verify the zoneID
https://github.com/Eein/octopath-autosplitter/blob/cf2d05691b76af0dd4941c9e29680f12c32fe3b2/octopath.asl#L403

**Comment by ak505188** [comment]
Figured this out, it's not Maw that's the issue, it's the area exit code in general. What happens is that entering an area and exiting an area happen at the same time, and entering the area takes priority. It worked on warps out because Enter Area made sure that gameState == 2, so if it was from a menu it wouldn't check and then the exit area code would run.

Yoszarian probably ran into this running Therion Single Story, where you exit Maw on foot, which is uncommon for areas we loot.
